# Generated by Django 3.2 on 2021-04-23 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Адрес')),
                ('level', models.SmallIntegerField(default=1, verbose_name='Уровень вложенности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256, verbose_name='Ссылка')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Скриншот')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
