# Generated by Django 3.2 on 2021-04-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Скриншот'),
        ),
        migrations.AlterField(
            model_name='links',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='main_app.tasks', verbose_name='Задача'),
        ),
    ]
