# Generated by Django 3.2 on 2021-04-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210424_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main_app.tasks', verbose_name='Задача'),
        ),
    ]
